### PR TITLE
Setting up conda-recipe.

### PR DESCRIPTION
**Pull request by bas-rustenburg**
Addressing what was suggested in #37.

Work in progress.

### CODE REVIEW

**Comment by jchodera** [comment]
Any luck with this?

**Comment by kyleabeauchamp** [comment]
Looks like we just need to get a conda recipe for `pint` on the omnia binstar and conda-recipes repo

**Comment by jchodera** [comment]
Do we want to put this into `omnia`?  I don't have a big problem with that---especially for now---but all the other tools are simulation tools, not experiment tools.

**Comment by kyleabeauchamp** [comment]
For now, I think it makes sense for users to need only a single extra channel.

We don't want this to be part of the omnia metapackage, though.  I'm just suggesting that we re-use the binstar channel, recipe repo, and  CI tools.

**Comment by jchodera** [comment]
Sounds like a plan for now!

We could have another metapackage called `choderalab` or `itcpack` or something.

**Comment by jchodera** [comment]
Let us know when this is ready to merge!

**Comment by bas-rustenburg** [comment]
Will do. Besides the conda dependencies, I need to fix something else that is wrong with my appveyor settings.

**Comment by bas-rustenburg** [comment]
Appveyor builds are now fixed to the point of the dependency not being met. I'm not sure if we should merge yet because I have not been able to test the remaining part of the recipe.

**Comment by bas-rustenburg** [comment]
Messed up the commit chain. Rebasing and resubmitting.

**Pull request closed without merging**
