### PR TITLE
Add missing install dependencies to setup.py

### PR DESCRIPTION
**Pull request by jchodera**
I added a bunch of missing dependencies to allow me to install `python setup.py install` and run `nosetests`.

### CODE REVIEW

**Comment by jchodera** [comment]
I'm not sure what the `setup_requires` and `test_requires` fields are in the `setup(...)` block.  Perhaps you can take a look at that?

**Comment by bas-rustenburg** [comment]
Sure! I believe they are specific to setuptools. Travis seems to work.  Appveyor might take a little while, though I don't expect issues. 

https://pythonhosted.org/setuptools/setuptools.html

**Comment by jchodera** [comment]
Should the added dependencies be added to `setup_requires`?

**Comment by bas-rustenburg** [comment]
I actually think we do not need that particular line since we're not using distutils extensions. We might as well get rid of it to prevent confusion in the future.

**Comment by jchodera** [comment]
> I actually think we do not need that particular line

Which particular line?

**Comment by bas-rustenburg** [comment]
The line with the `setup_requires` statement. `install_requires` only should also do the trick.

**Comment by bas-rustenburg** [comment]
Thanks!

**Pull request merged**
