### PR TITLE
Add CBS:CAII experiment

### PR DESCRIPTION
**Pull request by jchodera**
This PR adds an experiment based on the CAII:CBS training ITC experiments.

### CODE REVIEW

**Comment by jchodera** [comment]
@egoldber : I think you wanted to merge the branch rather than close it!

**Comment by jchodera** [comment]
@egoldber : But first I should probably add any other changes that might be needed here. Did we need to update anything else?  

My list had 
* Update scripts to output `csv` files for the PEAQ software in addition to Excel files for the Auto iTC-200 software

but I think that's it. Anything else I should do before we merge this?

**Comment by egoldber** [comment]
Actually, if you don't mind, I just tried to update the .gwl into EVO so we could use the DiTi Air LiHa instead of the fixed tips LiHa. For some reason the .gwl generates random `B;` (called a _"BreakOrder"_) into the worklist that causes a basically a reset and the EVO forgets if the LiHa has tips or not. Would it be possible to remove this additional `B;` from the script?

**Comment by egoldber** [comment]
> @egoldber : I think you wanted to merge the branch rather than close it!

Also, yes! My bad! Learning GitHub a bit slower than I'd like

**Comment by jchodera** [comment]
> Actually, if you don't mind, I just tried to update the .gwl into EVO so we could use the DiTi Air LiHa instead of the fixed tips LiHa. For some reason the .gwl generates random B; (called a "BreakOrder") into the worklist that causes a basically a reset and the EVO forgets if the LiHa has tips or not. Would it be possible to remove this additional B; from the script?

Yes, I can do this right now.

**Comment by jchodera** [comment]
I've added the option to generate LiHa or aLiHa worklists, and generated both for you in this ZIP file:
[caii.zip](https://github.com/choderalab/itctools/files/3764522/caii.zip)

Let me know if I should make other changes!

**Comment by jchodera** [comment]
I'm going to merge this. We can make further changes in a separate PR!

**Pull request merged**
